import os
import re

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")

# --- Known AI committer / co-author patterns ---
# Emails and trailer signatures used by popular AI coding tools
AI_EMAILS = {
    "noreply@github.com",           # generic, but used by bots
    "copilot@github.com",
    "github-actions[bot]@users.noreply.github.com",
}

AI_COAUTHOR_PATTERNS = [
    re.compile(r"Co-authored-by:.*GitHub\s*Copilot", re.IGNORECASE),
    re.compile(r"Co-authored-by:.*Cursor", re.IGNORECASE),
    re.compile(r"Co-authored-by:.*\bAI\b", re.IGNORECASE),
    re.compile(r"Co-authored-by:.*\bbot\b", re.IGNORECASE),
    re.compile(r"Generated by .*(Copilot|Cursor|ChatGPT|Claude)", re.IGNORECASE),
]

AI_COMMITTER_NAME_PATTERNS = [
    re.compile(r"\bcopilot\b", re.IGNORECASE),
    re.compile(r"\bcursor\b", re.IGNORECASE),
    re.compile(r"\[bot\]$", re.IGNORECASE),
]


def detect_ai_signals(commits: list) -> dict:
    """Scan commit data for AI-generated code signals.

    Returns a dict with:
      - ai_coauthor_found: bool — at least one AI co-author trailer was detected
      - ai_commits: int — number of commits with AI signals
      - total_commits: int — total number of commits examined
      - signals: list[str] — human-readable descriptions of each signal found
    """
    signals: list[str] = []
    ai_commit_count = 0

    for commit_obj in commits:
        commit = commit_obj.get("commit", {})
        message = commit.get("message", "")
        committer = commit.get("committer", {})
        author = commit.get("author", {})
        found_in_this_commit = False

        # Check commit message for Co-authored-by AI trailers
        for pattern in AI_COAUTHOR_PATTERNS:
            match = pattern.search(message)
            if match:
                signals.append(f"AI co-author trailer in commit: '{match.group().strip()}'")
                found_in_this_commit = True

        # Check committer email
        committer_email = (committer.get("email") or "").lower()
        if committer_email in AI_EMAILS:
            signals.append(f"Known AI committer email: {committer_email}")
            found_in_this_commit = True

        # Check committer / author name for bot patterns
        for name_field in [
            committer.get("name", ""),
            author.get("name", ""),
        ]:
            for pattern in AI_COMMITTER_NAME_PATTERNS:
                if pattern.search(name_field):
                    signals.append(f"AI committer/author name: '{name_field}'")
                    found_in_this_commit = True

        if found_in_this_commit:
            ai_commit_count += 1

    return {
        "ai_coauthor_found": len(signals) > 0,
        "ai_commits": ai_commit_count,
        "total_commits": len(commits),
        "signals": list(set(signals)),  # deduplicate
    }


# ------------------------------------------------------------------
# GitHub API helpers
# ------------------------------------------------------------------

import httpx
from urllib.parse import urlparse


def _build_headers():
    """Build GitHub API headers, only including Authorization if token exists."""
    h = {"Accept": "application/vnd.github.v3+json"}
    if GITHUB_TOKEN:
        h["Authorization"] = f"token {GITHUB_TOKEN}"
    return h


def parse_pr_url(pr_url: str):
    """Extract owner, repo, and pull number from a GitHub PR URL.
    Example: https://github.com/owner/repo/pull/123 -> ('owner', 'repo', 123)
    """
    parsed = urlparse(pr_url)
    parts = parsed.path.strip("/").split("/")
    if len(parts) < 4 or parts[2] != "pull":
        raise ValueError(
            f"Invalid GitHub PR URL. Expected format: https://github.com/owner/repo/pull/123  Got: {pr_url}"
        )
    owner, repo, number = parts[0], parts[1], parts[3]
    return owner, repo, int(number)


async def get_pr_details(owner: str, repo: str, number: int):
    """Fetch PR diff, commits, files changed, and review comments.
    Returns a dict with keys: pr, diff, commits, files, reviews, ai_signals.
    """
    headers = _build_headers()
    base = f"https://api.github.com/repos/{owner}/{repo}/pulls/{number}"

    async with httpx.AsyncClient(timeout=30.0, follow_redirects=True) as client:
        # PR metadata
        pr_resp = await client.get(base, headers=headers)
        pr_resp.raise_for_status()
        pr_json = pr_resp.json()

        # Diff (use the .diff URL directly)
        diff_headers = {**headers, "Accept": "application/vnd.github.v3.diff"}
        diff_resp = await client.get(base, headers=diff_headers)
        diff_resp.raise_for_status()
        diff_text = diff_resp.text

        # Commits
        commits_resp = await client.get(f"{base}/commits", headers=headers)
        commits_resp.raise_for_status()
        commits = commits_resp.json()

        # Files changed
        files_resp = await client.get(f"{base}/files", headers=headers)
        files_resp.raise_for_status()
        files = files_resp.json()

        # Review summaries (APPROVED, CHANGES_REQUESTED, etc.)
        reviews_resp = await client.get(f"{base}/reviews", headers=headers)
        reviews_resp.raise_for_status()
        reviews = reviews_resp.json()

        # Inline review comments (the actual line-by-line code feedback)
        comments_resp = await client.get(f"{base}/comments", headers=headers)
        comments_resp.raise_for_status()
        review_comments = comments_resp.json()

        # Also fetch top-level issue comments on the PR
        # (these are the non-inline discussion comments)
        issue_comments_url = f"https://api.github.com/repos/{owner}/{repo}/issues/{number}/comments"
        issue_comments_resp = await client.get(issue_comments_url, headers=headers)
        issue_comments_resp.raise_for_status()
        issue_comments = issue_comments_resp.json()

        # AI co-author / committer detection
        ai_signals = detect_ai_signals(commits)

        return {
            "pr": pr_json,
            "diff": diff_text,
            "commits": commits,
            "files": files,
            "reviews": reviews,
            "review_comments": review_comments,
            "issue_comments": issue_comments,
            "ai_signals": ai_signals,
        }
